### ISSUE TITLE
pytest-bdd throws error under python3.4

### ISSUE THREAD

**Issue by spinus** [olegpidsadnyi/pytest-bdd#93]
To reproduce:
```
virtualenv bdd -p python3.4 && bdd/bin/pip install pytest-bdd && bdd/bin/pytest-bdd
```
Output:
```
Traceback (most recent call last):
  File "bdd/bin/pytest-bdd", line 9, in <module>
    load_entry_point('pytest-bdd==2.5.3', 'console_scripts', 'pytest-bdd')()
  File "/home/spinus/tmp/bdd/lib/python3.4/site-packages/pytest_bdd/scripts.py", line 78, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

Also line 59 in setup.py:
```
] + [("Programming Language :: Python :: %s" % x) for x in "2.6 2.7 3.0 3.1 3.2 3.3".split()],
```
missing 3.4 but tox.ini has it.

**Comment by spinus** [comment]
Nice!
